// Generates the standalone, human-readable Vega-Lite/Vega specifications.
// These files can be opened independently in the Vega Editor with local data URLs replaced.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname,'..');
const summary = require('../data/team_summary.json');
const order=summary.map(d=>d.team);
const ink='#21372b',green='#31553b',sage='#a8bd9c',orange='#c96636',muted='#747c6f',grid='#dedfd4';
const config={background:'transparent',font:'Helvetica Neue, Arial, sans-serif',view:{stroke:null},axis:{domain:false,tickColor:grid,gridColor:grid,labelColor:muted,titleColor:muted,titleFontWeight:'normal',labelFontSize:15,titleFontSize:15,labelPadding:9,titlePadding:14,labelOverlap:true,labelLimit:150},legend:{labelColor:ink,titleColor:muted,labelFontSize:15,titleFontSize:15,orient:'bottom',titleFontWeight:'normal',padding:8},range:{category:[green,orange,'#aa9148','#838c76','#637963']}};
const base={ '$schema':'https://vega.github.io/schema/vega-lite/v5.json',width:'container',height:360,autosize:{type:'fit',contains:'padding',resize:true},padding:5,config};
const data=url=>({url:'data/'+url+'.json'});
const field=(field,type='quantitative',extra={})=>({field,type,...extra});
const tip=(field,title,format)=>({field,title,...(format?{format}:{}),type:['team','city','band'].includes(field)?'nominal':'quantitative'});
const save=(name,spec)=>fs.writeFileSync(path.join(root,'specs',name+'.json'),JSON.stringify({...base,...spec},null,2)+'\n');
const focus=[{name:'focusTeam',value:'All clubs'}];
const focused={condition:{test:"focusTeam === 'All clubs' || datum.team === focusTeam",value:1},value:0.22};
const years=[2012,2015,2018,2021,2025];

save('hero_finals',{description:'Geelong finals participation in each completed season from 2012 to 2025.',height:100,data:data('team_seasons'),transform:[{filter:"datum.team === 'Geelong'"}],encoding:{x:field('season','ordinal',{axis:{title:null,labelAngle:0,labelExpr:"datum.value == 2012 || datum.value == 2025 || (width >= 280 && (datum.value == 2015 || datum.value == 2020)) ? datum.label : ''",domain:false,ticks:false}})},layer:[{mark:{type:'bar',cornerRadiusTopLeft:1,cornerRadiusTopRight:1},encoding:{y:{value:5},y2:{value:60},color:{condition:{test:'datum.finalist === 1',value:green},value:'#d6dace'},tooltip:[tip('season','Season'),{field:'finalist',type:'nominal',title:'Played finals (1 = yes)'}]}}]});

save('ladder_heatmap',{description:'Regular-season ladder position, sorted by seasons reaching finals. Highlight a club using the page control.',height:530,data:data('team_seasons'),params:focus,encoding:{x:field('season','ordinal',{axis:{title:null,labelAngle:0,labelFontSize:15,labelExpr:"width < 420 ? (datum.value == 2012 || datum.value == 2018 || datum.value == 2025 ? datum.label : '') : datum.label"}}),y:field('team','nominal',{sort:order,axis:{title:null,labelFontSize:15,ticks:false,labelLimit:150}})},layer:[{mark:{type:'rect',stroke:'#f4f3eb',strokeWidth:3,cornerRadius:2},encoding:{color:field('band','nominal',{scale:{domain:['Top four','5th–8th','9th–18th'],range:[green,sage,'#e4e6da']},legend:null}),opacity:focused,tooltip:[tip('team','Club'),tip('season','Season'),tip('rank','Ladder position'),tip('wins','Wins'),tip('win_rate','Win rate (%)','.1f'),{field:'premier',type:'nominal',title:'Premier (1 = yes)'}]}},{mark:{type:'text',fontSize:15,fontWeight:500},encoding:{text:{condition:{test:'width >= 420',field:'rank',type:'quantitative'},value:''},color:{condition:{test:'datum.rank <= 4',value:'#ffffff'},value:'#324533'},opacity:focused}},{transform:[{filter:'datum.premier === 1'}],mark:{type:'point',shape:'diamond',filled:true,size:19,color:orange},encoding:{xOffset:{value:0},yOffset:{value:-10}}}]});

save('finals_frequency',{description:'Number of seasons in which each club played finals, out of 14.',height:475,data:data('team_summary'),params:focus,encoding:{y:field('team','nominal',{sort:order,axis:{title:null,ticks:false}}),x:field('finals','quantitative',{scale:{domain:[0,14]},axis:{title:'Seasons reaching finals',tickCount:8}}),opacity:focused,tooltip:[tip('team','Club'),tip('finals','Finals seasons'),tip('finals_rate','Share of seasons (%)','.1f')]},layer:[{mark:{type:'rule',strokeWidth:2,color:'#b8c4af'},encoding:{x2:{datum:0}}},{mark:{type:'point',filled:true,size:95,color:green}},{mark:{type:'text',align:'left',dx:9,fontSize:15,color:ink},encoding:{text:field('finals')}}]});

save('ladder_bump',{description:'Four contrasting clubs: regular-season ladder positions across 14 seasons. Lower ranks are better.',height:395,data:data('team_seasons'),transform:[{filter:{field:'team',oneOf:['Geelong','Hawthorn','Richmond','Brisbane Lions']}}],encoding:{x:field('season','quantitative',{scale:{domain:[2012,2026.2],nice:false},axis:{title:null,format:'d',values:years,grid:false}}),y:field('rank','quantitative',{scale:{domain:[18.5,0.5],nice:false},axis:{title:'Ladder position · 1st is best',values:[1,4,8,12,18]}}),color:field('team','nominal',{scale:{domain:['Geelong','Hawthorn','Richmond','Brisbane Lions'],range:[green,'#ad8b42','#777f76',orange]},legend:null}),tooltip:[tip('team','Club'),tip('season','Season'),tip('rank','Ladder position')]},layer:[{mark:{type:'line',strokeWidth:2.8,point:{filled:true,size:36}}},{transform:[{filter:'datum.season === 2025'}],mark:{type:'text',align:'left',dx:8,fontSize:15,fontWeight:600},encoding:{text:field('team','nominal')}}]});

const projection={type:'conicEqualArea',rotate:[-134,0,0],center:[0,-28],parallels:[-18,-36]};
const borders={url:'data/australia_states.topojson',format:{type:'topojson',feature:'states'}};
const mapBase={data:borders,mark:{type:'geoshape',fill:'#e3e6d9',stroke:'#f7f6ef',strokeWidth:1.2}};
const cityLabelLayer={data:data('cities'),transform:[{filter:'datum.grand_finals > 0'}],mark:{type:'text',align:'left',dx:7,dy:-8,fontSize:15,color:ink},encoding:{longitude:field('longitude'),latitude:field('latitude'),text:field('city','nominal')}};
save('state_choropleth',{description:'Finalist club-seasons divided by all club-seasons in each home state. Territories without an AFL club in 2012–2025 are not applicable.',height:400,projection,layer:[{data:borders,transform:[{lookup:'properties.state_code',from:{data:data('states'),key:'state_code',fields:['finals_rate','clubs','club_seasons','finals','coverage']}}],mark:{type:'geoshape',stroke:'#f7f6ef',strokeWidth:1.5,invalid:null},encoding:{color:{condition:{test:'datum.clubs > 0',field:'finals_rate',type:'quantitative',scale:{domain:[0,70],range:['#edf0de','#acbf94','#31553b']},legend:{title:'Club-seasons reaching finals (%)',gradientLength:190}},value:'#dedfd5'},tooltip:[{field:'properties.state_name',title:'State / territory',type:'nominal'},tip('clubs','Clubs'),tip('finals','Finalist club-seasons'),tip('club_seasons','Club-seasons'),tip('finals_rate','Finals rate (%)','.1f'),{field:'coverage',type:'nominal',title:'Coverage'}]}},{data:{values:[{label:'WA',lon:122,lat:-26},{label:'NT',lon:133,lat:-21},{label:'SA',lon:135,lat:-30},{label:'QLD',lon:145,lat:-22},{label:'NSW',lon:147,lat:-32},{label:'VIC',lon:143,lat:-36.7},{label:'TAS',lon:146.5,lat:-42}]},mark:{type:'text',fontSize:15,fontWeight:700,color:'#253f30'},encoding:{longitude:field('lon'),latitude:field('lat'),text:field('label','nominal')}}]});

const cityLabels=[{...cityLabelLayer,transform:[{filter:"datum.grand_finals > 0 && datum.city !== 'Geelong' && datum.city !== 'Melbourne'"}]},{...cityLabelLayer,transform:[{filter:"datum.city === 'Melbourne'"}],mark:{type:'text',align:'left',dx:15,dy:-6,fontSize:15,color:ink}},{...cityLabelLayer,transform:[{filter:"datum.city === 'Geelong'"}],mark:{type:'text',align:'right',dx:-7,dy:20,fontSize:15,color:ink}}];
save('premiership_symbols',{description:'Premiership totals aggregated by club home city. Circle area, not radius, represents title count. Melbourne and Geelong are separate cities.',height:360,projection,layer:[mapBase,{data:data('cities'),transform:[{filter:'datum.premierships > 0'}],mark:{type:'circle',color:orange,opacity:0.65,stroke:orange,strokeWidth:1},encoding:{longitude:field('longitude'),latitude:field('latitude'),size:field('premierships','quantitative',{scale:{domain:[0,9],range:[0,1700]},legend:{title:'Premierships',values:[1,3,9],orient:'bottom'}}),tooltip:[tip('city','Home city'),tip('clubs','Clubs'),tip('premierships','Premierships')]}},...cityLabels]});

save('grand_final_flows',{description:'Connections between the home cities of Grand Final opponents. Line width represents the number of matchups, not physical journeys. Same-city final excluded.',height:360,projection,layer:[mapBase,{data:data('finals_connections'),mark:{type:'geoshape',filled:false,stroke:green,opacity:0.65},encoding:{strokeWidth:field('properties.count','quantitative',{scale:{domain:[1,5],range:[1.5,9]},legend:{title:'Grand Final meetings',values:[1,3,5],orient:'bottom'}}),tooltip:[{field:'properties.pair',type:'nominal',title:'Club home cities'},{field:'properties.count',type:'quantitative',title:'Meetings'},{field:'properties.years',type:'nominal',title:'Seasons'}]}},{data:data('cities'),transform:[{filter:'datum.grand_finals > 0'}],mark:{type:'circle',color:green,opacity:1,size:45,stroke:'#f3f2e9',strokeWidth:1.5},encoding:{longitude:field('longitude'),latitude:field('latitude'),tooltip:[tip('city','Home city'),tip('grand_finals','Grand Final appearances')]}},...cityLabels]});

save('season_boxplot',{description:'Distribution of regular-season win rates for each club over 14 seasons. Box covers the middle half; line is median; whiskers cover the full range.',height:490,data:data('team_seasons'),encoding:{y:field('team','nominal',{sort:order,axis:{title:null,ticks:false}}),x:field('win_rate','quantitative',{scale:{domain:[0,100]},axis:{title:'Regular-season games won (%)',tickCount:6}})},mark:{type:'boxplot',extent:'min-max',size:13,color:sage,median:{color:green,strokeWidth:2},rule:{color:'#8f9f84'},ticks:{color:'#8f9f84'}}});

save('finals_streaks',{description:'Consecutive runs of finals appearances, with gaps for seasons without finals.',height:475,data:data('streaks'),encoding:{x:field('start','quantitative',{scale:{domain:[2011.5,2025.5],nice:false},axis:{title:null,format:'d',values:years}}),x2:field('end'),y:field('team','nominal',{sort:order,axis:{title:null,ticks:false}}),color:field('length','quantitative',{scale:{domain:[1,7],range:['#b5c6a7',green]},legend:null}),tooltip:[tip('team','Club'),tip('first','First season','d'),tip('last','Last season','d'),tip('length','Consecutive finals seasons')]},mark:{type:'bar',size:13,cornerRadius:2}});

save('era_dumbbell',{description:'Aggregate regular-season win rate in 2012–2018 compared with 2019–2025. Denominators use games played in each period.',height:475,data:data('team_summary'),encoding:{y:field('team','nominal',{sort:{field:'change',order:'descending'},axis:{title:null,ticks:false}}),x:field('early_rate','quantitative',{scale:{domain:[0,100]},axis:{title:'Regular-season games won (%)',tickCount:6}}),tooltip:[tip('team','Club'),tip('early_rate','2012–2018 win rate (%)','.1f'),tip('recent_rate','2019–2025 win rate (%)','.1f'),tip('change','Change (percentage points)','+.1f')]},layer:[{mark:{type:'rule',strokeWidth:2.5,color:'#b5c3a8'},encoding:{x2:field('recent_rate')}},{mark:{type:'point',filled:true,fill:'#f3f2e9',stroke:green,strokeWidth:1.5,size:60}},{mark:{type:'point',filled:true,size:80},encoding:{x:field('recent_rate'),color:{condition:{test:'datum.change >= 0',value:green},value:orange}}}]});

save('success_scatter',{description:'Overall regular-season win rate versus seasons reaching finals. Highlights the relationship between sustained winning and finals participation.',height:360,data:data('team_summary'),encoding:{x:field('win_rate','quantitative',{scale:{domain:[20,77],zero:false},axis:{title:'Regular-season games won (%)',tickCount:6}}),y:field('finals','quantitative',{scale:{domain:[0,14]},axis:{title:'Seasons reaching finals',tickCount:8}}),tooltip:[tip('team','Club'),tip('win_rate','Win rate (%)','.1f'),tip('finals','Finals seasons'),tip('premierships','Premierships')]},layer:[{mark:{type:'point',filled:true,size:115,stroke:'#f3f2e9',strokeWidth:1},encoding:{color:{condition:{test:'datum.premierships > 0',value:orange},value:green}}},{transform:[{filter:{field:'team',oneOf:['Geelong','Sydney','Hawthorn','Brisbane Lions','Gold Coast']}}],mark:{type:'text',align:'left',dx:8,dy:-8,color:ink,fontSize:15},encoding:{text:field('team','nominal')}}]});

const tree=[{team:'AFL',parent:null,premierships:0},...summary.filter(d=>d.premierships).map(d=>({team:d.team,parent:'AFL',premierships:d.premierships}))];
fs.writeFileSync(path.join(root,'data/premiership_tree.json'),JSON.stringify(tree,null,2)+'\n');
const treemap={
 '$schema':'https://vega.github.io/schema/vega/v5.json',description:'Every rectangle represents a premiership-winning club; its area is proportional to titles in 2012–2025.',width:600,height:330,padding:0,autosize:{type:'none',resize:true},background:'transparent',
 data:[{name:'tree',url:'data/premiership_tree.json',transform:[{type:'stratify',key:'team',parentKey:'parent'},{type:'treemap',field:'premierships',sort:{field:'value',order:'descending'},method:'squarify',ratio:1.4,size:[{signal:'width'},{signal:'height'}],paddingInner:5}]},{name:'leaves',source:'tree',transform:[{type:'filter',expr:'!datum.children'}]}],
 scales:[{name:'fill',type:'ordinal',domain:['Hawthorn','Richmond','Brisbane Lions','Geelong','Sydney','Collingwood','Western Bulldogs','West Coast','Melbourne'],range:['#a07740',green,'#a14e36','#496c4d','#65845d','#72876b','#839278','#506b51','#6b7e5c']}],
 marks:[{type:'rect',from:{data:'leaves'},encode:{enter:{stroke:{value:'#f3f2e9'},strokeWidth:{value:1}},update:{x:{field:'x0'},y:{field:'y0'},x2:{field:'x1'},y2:{field:'y1'},fill:{scale:'fill',field:'team'},tooltip:{signal:"{'Club':datum.team,'Premierships':datum.premierships,'Share of titles':format(datum.premierships/14,'.0%')}"}}}},
 {type:'text',from:{data:'leaves'},encode:{enter:{fill:{value:'#fffdf4'},font:{value:'Helvetica Neue, Arial, sans-serif'},fontSize:{value:32},fontWeight:{value:700},baseline:{value:'top'}},update:{x:{signal:'datum.x0 + 12'},y:{signal:'datum.y0 + 12'},text:{field:'premierships'}}}},
 {type:'text',from:{data:'leaves'},encode:{enter:{fill:{value:'#fffdf4'},font:{value:'Helvetica Neue, Arial, sans-serif'},fontSize:{value:15},fontWeight:{value:500},baseline:{value:'bottom'}},update:{x:{signal:'datum.x0 + 12'},y:{signal:'datum.y1 - 13'},text:{field:'team'},limit:{signal:'datum.x1 - datum.x0 - 22'}}}}
 ]};
fs.writeFileSync(path.join(root,'specs/premiership_treemap.json'),JSON.stringify(treemap,null,2)+'\n');
console.log('Created 11 main chart specs and the hero mini-chart.');
